targets:
  $default:
    sources:
      - extra/**
      - lib/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "extra"
          output_folder: "lib/api"
        additional_headers:
          - ''